# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a8870d23057dd4b986d6dc5e8060ee485d1731463a7e80b311c66a80b97babb899a0651b6c4bdfc00064c6a10497be6a9365fb191780c2eedf05fa57bb4142d

test:
  secret_key_base: 34e1bfa15cfb6d87794726567c015f3b53e2a3e9c668dec01dc5b2dbcd51258a371d301701e08368fa902f1bc26ddaffaa35ae83e1a1fab0e62de4899b74b882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
